### ISSUE TITLE
Use WP query APIs whenever possible

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/Co-Authors-Plus-Roles#6]
For instance, this SELECT should use `get_post_meta()` or similar:

```
$coauthor_ids = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT * FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key IN {$meta_key_in};",
				array( $post_id )
			)
		);
```

At the very least, the query APIs make it easier to plug into object caching.

**Comment by danielbachhuber** [comment]
Another instance:

```
$drop_existing_role = $wpdb->query(
		$wpdb->prepare(
			"DELETE FROM {$wpdb->postmeta} WHERE post_id=%d AND meta_key LIKE 'cap-%%' AND meta_value=%d",
			array( $post_id, $author->ID )
		)
	);
```

Using `delete_post_meta()` means the post object cache is properly cleared.

**Comment by goldenapples** [comment]
Hmm. I don't think either of these queries would work well with the WordPress meta query APIs.

For the first one, I'm selecting all meta values where the key is in the array of possible keys, there isn't a simple way with get_post_meta to do that. But I suppose I could loop through the possible key values and call get_post_meta on each of them.

The second one is tougher, because the possible key values aren't even limited to an array that I could iterate over - because a role could have been deleted or de-registered. I was thinking it would be way too inefficient to get all the post meta into memory and inspect them all.

**Comment by danielbachhuber** [comment]
> But I suppose I could loop through the possible key values and call get_post_meta on each of them.

You should do this. The meta will already exist in object cache, so you're avoiding a SQL query.

> I was thinking it would be way too inefficient to get all the post meta into memory and inspect them all.

VIP opts for PHP inefficiency over database dependency, because the latter is a more problematic source of failure at scale.
